# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7799f4f1cdbe22433beb58b449fdf71a5ff718022fc7d976ac08c0550561a2b778b2e92bb2ea5d161fbb4359129154f57ffd64c82bcdc81dc2c1978a1483054e

test:
  secret_key_base: b22f2bff36a9a06a21cb82f8ade7ba17e52997cc5a98d8371228b2c90ee53153e8371cd527f5003080a5dc6da5289379359e5fa131731ceb6371a94031085d6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
